# Generated by Django 5.1.4 on 2024-12-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.PositiveIntegerField()),
                ('bill_items', models.CharField(max_length=255)),
                ('bill_address', models.CharField(max_length=255)),
                ('bill_amount', models.FloatField()),
                ('bill_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField()),
                ('product_category', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('product_quantity', models.IntegerField()),
                ('product_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Stock_id', models.IntegerField()),
                ('Stock_number', models.IntegerField(default=0)),
            ],
        ),
    ]
